language: c 

cache:
    apt: true

os:
    - linux
    - osx

env:
    - TEST_SUITE=short
    - TEST_SUITE=cx
    - TEST_SUITE=long
    - TEST_SUITE=relativistic
    - TEST_SUITE=geminal

osx_image: xcode7.3
# Could add more toolchains in future
# with something like:
#
# sources:
#   - ubuntu-toolchain-r-test
# packages:
#   - gfortran-6.1
#
# or similar
addons:
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - perl
            - cmake
            - cmake-data
            - gfortran
            - liblapack-dev
            - numdiff

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install homebrew/science/numdiff; fi

# We are only really interested in the short tests for now
script:
  - mkdir build && cd build
  - cmake --version
  - cmake ..
  - cmake --build .
  - ctest -L $TEST_SUITE

notifications:
  email: false
  slack: quantum-crystals:c4wMeP4do0xwgnNyHuGefmQH
